options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [
      '-c',
      'gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS && \
       gcloud config set project $PROJECT_ID && \
       gcloud config set compute/zone us-central1-c && \
       gcloud auth configure-docker us-central1-docker.pkg.dev/$PROJECT_ID/k8-jems'
    ]

  - name: 'docker:dind'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd Container1 && \
       docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/k8-jems/k8s-container1:latest . && \
       docker push us-central1-docker.pkg.dev/$PROJECT_ID/k8-jems/k8s-container1:latest && \
       cd .. && \
       cd Container2 && \
       docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/k8-jems/k8s-container2:latest . && \
       docker push us-central1-docker.pkg.dev/$PROJECT_ID/k8-jems/k8s-container2:latest && \
       cd ..'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [
      '-c',
      'gcloud container clusters get-credentials k8s-assignment && \
       cd deployment && \
       kubectl apply -f deployment.yml && \
       cd ..'
    ]

substitutions:
  _GCP_PROJECT: 'cloud-428816'
  _GKE_CLUSTER: 'k8s-assignment'
  _GKE_ZONE: 'us-central1-c'
  _KUBERNETES_NAMESPACE: 'default'
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev/cloud-428816/k8-jems'

timeout: '1200s'
